################################################################################
###                     Dependency configuration                             ###
################################################################################
spring:
  cloud:
    kubernetes:
      # Kubernetes discovery client
      discovery:
        # Enabled by default
        enabled: false

      # Custom directives from here down
      service:
        # Kubernetes service discovery client
        discovery:
          # Enabled by default
          enabled: true

    discovery:
      client:
        simple:
          instances:
              1-local-bodyshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs.poll]": true
                  "[swagger.io/apidocs.host]": 127.0.0.1
                  # "[swagger.io/apidocs.port]": 10080
                  # "[swagger.io/apidocs.path]": /not-existing

              2-local-paintshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs.poll]": false

################################################################################
###                      Custom directives                                   ###
################################################################################

################################################################################
###                       Logging configuration                              ###
################################################################################
# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

# Springfox
# logging.level.springfox.documentation: DEBUG

# This application
