################################################################################
###                     Dependency configuration                             ###
################################################################################
spring:
  application:
    name: swagger-aggregator

  cloud:
    kubernetes:
      # Kubernetes discovery client
      discovery:
        # Enabled by default
        enabled: true

# Display application name in Actuator's info endpoint 
info.app.name: ${spring.application.name}

management:
  # To change which endpoints are exposed, use 
  # management.endpoints.web.exposure.include and  
  # management.endpoints.web.exposure.exclude properties.
  endpoints:
    web:
      exposure:
        # Expose all actuator endpoints
        include: '*'

################################################################################
###                      Custom directives                                   ###
################################################################################
# API documentation path where aplication defaults when path is not in service metadata
documentation.swagger.v2.defaultpath: /api-docs


aggregator:
  documentation:
    # Default path to Swagger API documentation in JSON format. On client side 
    # it is configured by: 
    #    documentation.swagger.v2.defaultpath and defualts to /v2/api-docs   
    # Aplication defaults to this when path is not in service metadata.
    # Default value: /v2/api-docs
    swagger.v2.defaultpath: /api-docs

    # Path to 
    api-docs-proxy.path: /api-docs/proxy

################################################################################
###                       Logging configuration                              ###
################################################################################
logging.level: INFO
logging.level.org.springframework: INFO
logging.level.org.apache: WARN
logging.level.org.apache.tomcat: INFO
logging.level.org.hibernate: INFO
logging.level.org.thymeleaf: INFO
logging.level.net.michalfoksa: TRACE
