################################################################################
###                     Dependency configuration                             ###
################################################################################
spring:
  cloud:
    kubernetes:
      # Kubernetes discovery client
      discovery:
        # Enabled by default
        enabled: false

      # Custom directives from here down
      service:
        # Kubernetes service discovery client
        discovery:
          # Enabled by default
          enabled: true

    discovery:
      client:
        simple:
          instances:
              bodyshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs/poll]": true
              paintshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs/poll]": false

################################################################################
###                      Custom directives                                   ###
################################################################################

################################################################################
###                       Logging configuration                              ###
################################################################################
# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

# Springfox
# logging.level.springfox.documentation: DEBUG

# This application
