################################################################################
###                     Dependency configuration                             ###
################################################################################
spring:
  cloud:
    kubernetes:
      # Kubernetes discovery client
      discovery:
        # Enabled by default
        enabled: false

        ###############################################################################################################
        ###                Filter examples in Spring Expression Language (SpEL)                                     ###
        ### See: https://docs.spring.io/spring/docs/4.3.10.RELEASE/spring-framework-reference/html/expressions.html ###
        ### and https://dzone.com/articles/learn-spring-expression-language-with-examples                           ###
        ###############################################################################################################
        # Return service called bodyshop
        # filter: metadata.name == 'bodyshop'
        # Return service name end with 'shop'
        # filter: metadata.name matches '.*shop'
        # Return services where annotation "swagger.io/apidocs.poll == true".
        # filter: metadata.annotations['swagger.io/apidocs.poll'] == 'true'

      # Custom directives from here down
      service:
        # Kubernetes service discovery client
        discovery:
          # Enabled by default
          enabled: true

    discovery:
      client:
        simple:
          instances:
              1-local-bodyshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs.poll]": true
                  "[swagger.io/apidocs.host]": 127.0.0.1
                  # "[swagger.io/apidocs.port]": 10080
                  "[swagger.io/apidocs.path]": /api-docs

              2-local-paintshop:
              - uri: http://localhost:10081/
                metadata:
                  "[swagger.io/apidocs.poll]": true
                  "[swagger.io/apidocs.path]": /api-docs

################################################################################
###                      Custom directives                                   ###
################################################################################

################################################################################
###                       Logging configuration                              ###
################################################################################
# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

# Springfox
# logging.level.springfox.documentation: DEBUG

# This application
