---
kind: Service
apiVersion: v1
metadata:
  name: workstation-link
  annotations:
    swagger.io/apidocs.path: /api-docs
    swagger.io/apidocs.poll: "true"
spec:
  type: ExternalName
  # Target service DNS name
  externalName: workstation.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: bodyshop-link
  annotations:
    swagger.io/apidocs.path: /api-docs
    swagger.io/apidocs.poll: "true"
spec:
  type: ExternalName
  # Target service DNS name
  externalName: bodyshop.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: paintshop-link
  annotations:
    swagger.io/apidocs.path: /api-docs
    swagger.io/apidocs.poll: "true"
spec:
  type: ExternalName
  # Target service DNS name
  externalName: paintshop.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80
