---
kind: Service
apiVersion: v1
metadata:
  name: workstation-link
spec:
  type: ExternalName
  # Target service DNS name
  externalName: workstation.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: bodyshop-link
spec:
  type: ExternalName
  # Target service DNS name
  externalName: bodyshop.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: paitshop-link
spec:
  type: ExternalName
  # Target service DNS name
  externalName: paitshop.jx-staging.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 80
